# Generated by Django 5.2.3 on 2025-06-19 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("idx", models.AutoField(primary_key=True, serialize=False)),
                ("board_idx", models.IntegerField()),
                ("writer", models.CharField(max_length=50)),
                ("content", models.TextField()),
                (
                    "post_date",
                    models.DateField(blank=True, default=datetime.datetime.now),
                ),
            ],
        ),
    ]
